@del col.tmp
@del col2.tmp
@del allcol.col
@call mc bg2-a 0 7
@call mc bg2-b 0 13
@call mc bg2-c 0 7
@call mc bg2-d 0 7
@call mc bg2-e 0 9
@call mc bg2-f 0 7
@call mc bg2-g 0 7
@call mc t-m 0 7
@call mc t-m-2 0 7
@call mc t-m-3 0 7
@call mc t-m-4 0 7
@call mc b-m 0 7
@call mc light 0 7
@call mc space 0 7
@call mc stars 0 7
@call mc cp 0 7
@call mc cp-us 0 7
@call mc hole 0 7
@call mc l 0 7
@call mc e-test0 0 7
@call mc e-test 0 7
@call mc obj-1 8 13
@call mc 2ep 0 9
@call mc fxdes 0 7
@call mc fxblue 0 7
@call mc fxgreen 0 7
@call mc fxpink 0 7
@call mc fortn 0 7
@call mc corn 0 7
@call mc newspace 0 7
@call mc vortex 0 7
@call mc city 0 7
@call mc corn2 0 7
@packer /4000 allcol.col allcol.pac