#########################
# UltraStarFox Makefile #
#########################

# Assembler
ASM=ARGSFXX
# Setup heap for SASM and export symbols for ARGSFX
ASMFLAGS= -e__heap=14400 -z

# Linker
LINK=ARGLINK
LOPTS=-b30 -h1024 -t7d -z

# ROM Extender
EXTEND=EXTEND
# Extended size in Mbits, byte to pad with
EXTOPS= 16 ff

# Checksum Fixer
CHECK=SFCHECK
COPTS=-s -f

# FXGFX Interleaver
MERGE=MERGE
MOPTS= /cgx

# Graphics Cruncher
CRU=CRU

# Font Converter
FONT=FON

# Argonaut .MAP File Decoder
MAPDEC=MAPDEC

#!! If you add/remove a cgx/scr in these two lists, make sure to add/remove the corresponding file.

# Crunched tilesets
CGXFILES= DATA\1-3-B.CCR DATA\2-3B.CCR DATA\3-4.CCR DATA\B.CCR DATA\CONT.CCR DATA\DOG.CCR \
 DATA\F-1.CCR DATA\FS-BG3.CCR DATA\MAP-G.CCR DATA\OBJ-2.CCR DATA\SPACE.CCR DATA\T-ST.CCR \
 DATA\1-4.CCR DATA\2-4.CCR DATA\AND.CCR DATA\C-M.CCR DATA\CP-P.CCR DATA\E-TEST.CCR \
 DATA\F-OBJ.CCR DATA\HOLE-A.CCR DATA\MAP.CCR DATA\OBJ-3.CCR DATA\ST-P.CCR DATA\TI-3-G.CCR \
 DATA\2-2.CCR DATA\3-2.CCR DATA\B-HOLE.CCR DATA\CONT-2-G.CCR DATA\CP.CCR DATA\E-TEST2.CCR \
 DATA\FOX-G.CCR DATA\LSB.CCR DATA\OBJ-1-G.CCR DATA\OBJ-4.CCR DATA\OOPS.CCR DATA\STARS.CCR \
 DATA\TI-3-US.CCR DATA\2-3.CCR DATA\3-3.CCR DATA\B-M.CCR DATA\CONT-2.CCR DATA\DEMO.CCR \
 DATA\FOX.CCR DATA\M.CCR DATA\OBJ-1.CCR DATA\T-SP.CCR DATA\TI-3.CCR

# Crunched tilemaps
SCRFILES= DATA\1-3-B.PCR DATA\2-3.PCR DATA\3-2.PCR DATA\B-HOLE.PCR DATA\CONT.PCR DATA\DOG.PCR \
 DATA\F-1.PCR DATA\LAST.PCR DATA\T-SP.PCR DATA\TI-3-US.PCR DATA\1-3.PCR DATA\2-3B.PCR \
 DATA\3-3.PCR DATA\B.PCR DATA\CP-P.PCR DATA\E-TEST.PCR DATA\FOX.PCR DATA\LSB.PCR DATA\ST-P.PCR \
 DATA\T-SS.PCR DATA\TI-3.PCR DATA\1-4.PCR DATA\2-3H.PCR DATA\3-4.PCR DATA\CONT-2-G.PCR \
 DATA\CP.PCR DATA\E-TEST2.PCR DATA\FS-NI.PCR DATA\M.PCR DATA\OOPS.PCR DATA\STARS.PCR DATA\T-ST.PCR \
 DATA\2-2.PCR DATA\2-4.PCR DATA\AND.PCR DATA\CONT-2.PCR DATA\DEMO.PCR DATA\HOLE-A.PCR DATA\MAP.PCR \
 DATA\T-F-S.PCR DATA\TI-3-G.PCR

#!! If you add/remove a font, make sure to add/remove the corresponding file.

# Font files converted from BMP
FONFILES= DATA\FONT\MOJI_0.FON DATA\FONT\MOJI_D.FON

# Banks to assemble
ALLFILES= BANK\BANK0.SOB BANK\BANK1.SOB BANK\BANK2.SOB \
 BANK\BANK4.SOB BANK\BANK5.SOB BANK\BANK6.SOB BANK\BANK7.SOB \
 BANK\BANK8.SOB BANK\BANK9.SOB BANK\BANK10.SOB \
 BANK\BANK11.SOB BANK\SHBANKS.SOB BANK\INCBINS.SOB

# Recipe to assemble a .ASM file and create a linkable .SOB file
.asm.sob:
	@$(ASM) $(NOANSI) -m30 $(ASMFLAGS) $< -v$*.SOB

# Recipes to crunch graphics
.cgx.ccr:
	@$(CRU) $< $*.CCR

.scr.pcr:
	@$(CRU) $< $*.PCR

# Recipe to convert BMP to FON
.bmp.fon:
	@$(FONT) $<

# Everything that should be done when make is executed
all: setup allcols msprites crunch fonts sf.sfc donebld

setup:
	@del BANK\*.SOB
	@del BANK\*.MAP

# Recipe to crunch palettes
allcols:
	@cd DATA\COL
	@pc.bat
	@cd ..\..

#!! If you add/remove/modify a cgx/bin in these two lists, make sure the corresponding files are present here.

# FXGFX files to be interleaved
msprites: tex_01.bin tex_23.bin tex_23_a.bin

# MSPRITES .BIN recipes
tex_01.bin:
	@$(MERGE) MSPRITES\tex_0.CGX MSPRITES\tex_1.CGX MSPRITES\$@ $(MOPTS)

tex_23.bin:
	@$(MERGE) MSPRITES\tex_2.CGX MSPRITES\tex_3.CGX MSPRITES\$@ $(MOPTS)

tex_23_a.bin:
	@$(MERGE) MSPRITES\tex_2.CGX MSPRITES\tex_3_a.CGX MSPRITES\$@ $(MOPTS)

# Crunch all compressible GFX
crunch: $(CGXFILES) $(SCRFILES)

# Convert fonts
fonts: $(FONFILES)

# The ROM Itself
sf.sfc: $(ALLFILES)
	@$(LINK) $(LOPTS) -o$@ @flist
	@$(EXTEND) $@ $(EXTOPS)
	@$(CHECK) $(COPTS) $@

# Actions to perform when assembly is completed
donebld:
	@del msgs.txt
	@del BANK\*.SOB
	@del BANK\*.MAP
	@copy sf.sfc ..\SF.sfc
	@del sf.sfc
	@$(MAPDEC) SF.MAP SYMBOLS.TXT
	@del SF.MAP
	@copy SYMBOLS.TXT ..\SYMBOLS.TXT
	@del SYMBOLS.TXT
	@copy BANKS.CSV ..\BANKS.CSV
	@del BANKS.CSV

# Clean everything up
clean:
	@del BANK\*.SOB
	@del BANK\*.MAP
	@del *.MAP
	@del MSPRITES\*.BIN
	@del DATA\COL\ALLCOLS.COL
	@del DATA\COL\*.PAC
	@del DATA\COL\*.TMP
	@del DATA\*.CCR
	@del DATA\*.PCR
	@del msgs.txt
	@del ..\sf.sfc
	@del sf.sfc
	@del ..\build.log
	@del ..\BANKS.CSV
	@del BANKS.CSV
	@del SYMBOLS.TXT
	@del ..\SYMBOLS.TXT

## Banks to assemble

## Banks 0, 32
BANK0.SOB: \
BANK\BANK0.ASM

## Banks 1, 41
BANK1.SOB: \
BANK\BANK1.ASM

## Banks 2, 3, 31, 36
BANK2.SOB: \
BANK\BANK2.ASM

## Bank 4
BANK4.SOB: \
BANK\BANK4.ASM

## Banks 5, 13, 39
BANK5.SOB: \
BANK\BANK5.ASM

## Banks 6, 33
BANK6.SOB: \
BANK\BANK6.ASM

## Bank 7
BANK7.SOB: \
BANK\BANK7.ASM

## Bank 8
BANK8.SOB: \
BANK\BANK8.ASM \

## Bank 9
BANK9.SOB: \
BANK\BANK9.ASM

## Bank 10
BANK10.SOB: \
BANK\BANK10.ASM

## Banks 11, 40
BANK11.SOB: \
BANK\BANK11.ASM

## Banks 12, 14, 15, 16, 17, 37, 38
SHBANKS.SOB: \
BANK\SHBANKS.ASM

## Banks 18, 19, 20, 21, 22, 23, 35 
INCBINS.SOB: \
BANK\INCBINS.ASM


