#####################
# Star Fox Makefile #
#####################

ASM=SASMX
ASMFLAGS=-efilelist=0 -xsymbols.txt
LINK=ARGLINK
LOPTS=-b30 -h1024 -t7d
EXTEND=EXTEND
EXTOPS= 16 ff
CHECK=SFCHECK
COPTS=-s -f

ALLFILES= BANK\bank0.sob BANK\bank1.sob BANK\bank2.sob \
 BANK\bank4.sob BANK\bank5.sob BANK\bank6.sob BANK\bank7.sob \
 BANK\bank8.sob BANK\bank9.sob BANK\bank10.sob \
 BANK\bank11.sob BANK\shbanks.sob BANK\incbins.sob

.asm.sob:
	@$(ASM) -m30 $(ASMFLAGS) $< -v$*.SOB

all: sg.rom

sg.rom: $(ALLFILES)
	@$(LINK) $(LOPTS) -osg.rom @flist
    @$(EXTEND) sg.rom $(EXTOPS)
	@$(CHECK) $(COPTS) sg.rom

## Files to assemble
bank0.sob: BANK\bank0.asm

bank1.sob: BANK\bank1.asm

bank2.sob: BANK\bank2.asm

bank4.sob: BANK\bank4.asm

bank5.sob: BANK\bank5.asm

bank6.sob: BANK\bank6.asm

bank7.sob: BANK\bank7.asm

bank8.sob: BANK\bank8.asm

bank9.sob: BANK\bank9.asm

bank10.sob: BANK\bank10.asm

bank11.sob: BANK\bank11.asm

shbanks.sob: BANK\shbanks.asm

incbins.sob: BANK\incbins.asm


