#########################
# UltraStarFox Makefile #
#########################

# Assembler
ASM=SASMX
ASMFLAGS=-efilelist=0 -xsymbols.txt

# Linker
LINK=ARGLINK
LOPTS=-b30 -h1024 -t7d

# ROM Extender
EXTEND=EXTEND
# Extended size in Mbits, byte to pad with
EXTOPS= 16 ff

# Checksum Fixer
CHECK=SFCHECK
COPTS=-s -f

# FXGFX Interleaver
MERGE=MERGE
MOPTS= /cgx

# Graphics Cruncher
CRU=CRU

# Compressible GFX
CGXFILES= DATA\1-3-B.CCR DATA\2-3B.CCR DATA\3-4.CCR DATA\B.CCR DATA\CONT.CCR DATA\DOG.CCR \
 DATA\F-1.CCR DATA\FS-BG3.CCR DATA\MAP-G.CCR DATA\OBJ-2.CCR DATA\SPACE.CCR DATA\T-ST.CCR \
 DATA\TI.CCR DATA\1-4.CCR DATA\2-4.CCR DATA\AND.CCR DATA\C-M.CCR DATA\CP-G.CCR DATA\E-TEST.CCR \
 DATA\F-OBJ.CCR DATA\HOLE-A.CCR DATA\MAP.CCR DATA\OBJ-3.CCR DATA\ST-P.CCR DATA\TI-3-G.CCR DATA\2-2.CCR \
 DATA\3-2.CCR DATA\B-HOLE.CCR DATA\CONT-2-G.CCR DATA\CP.CCR DATA\E-TEST2.CCR DATA\FOX-G.CCR DATA\LSB.CCR \
 DATA\OBJ-1-G.CCR DATA\OBJ-4.CCR DATA\STARS.CCR DATA\TI-3-US.CCR DATA\2-3.CCR DATA\3-3.CCR DATA\B-M.CCR \
 DATA\CONT-2.CCR DATA\DEMO.CCR DATA\E.CCR DATA\FOX.CCR DATA\M.CCR DATA\OBJ-1.CCR DATA\SC.CCR DATA\T-SP.CCR \
 DATA\TI-3.CCR

SCRFILES= DATA\1-3-B.PCR DATA\2-3.PCR DATA\3-2.PCR DATA\B-HOLE.PCR DATA\CONT.PCR DATA\DOG.PCR \
 DATA\F-1.PCR DATA\LAST.PCR DATA\SC.PCR DATA\T-SP.PCR DATA\TI-3-US.PCR DATA\1-3.PCR \
 DATA\2-3B.PCR DATA\3-3.PCR DATA\B.PCR DATA\CP-G.PCR DATA\E-TEST.PCR DATA\FOX.PCR \
 DATA\LSB.PCR DATA\ST-P.PCR DATA\T-SS.PCR DATA\TI-3.PCR DATA\1-4.PCR DATA\2-3H.PCR \
 DATA\3-4.PCR DATA\CONT-2-G.PCR DATA\CP.PCR DATA\E-TEST2.PCR DATA\FS-NI.PCR DATA\M.PCR \
 DATA\STARS.PCR DATA\T-ST.PCR DATA\TI.PCR DATA\2-2.PCR DATA\2-4.PCR DATA\AND.PCR \
 DATA\CONT-2.PCR DATA\DEMO.PCR DATA\E.PCR DATA\HOLE-A.PCR DATA\MAP.PCR DATA\T-F-S.PCR \
 DATA\TI-3-G.PCR

# Banks that should be assembled
ALLFILES= BANK\bank0.sob BANK\bank1.sob BANK\bank2.sob \
 BANK\bank4.sob BANK\bank5.sob BANK\bank6.sob BANK\bank7.sob \
 BANK\bank8.sob BANK\bank9.sob BANK\bank10.sob \
 BANK\bank11.sob BANK\shbanks.sob BANK\incbins.sob

# Recipe to assemble a .ASM file and create a linkable .SOB file
.asm.sob:
	@$(ASM) -m30 $(ASMFLAGS) $< -v$*.SOB

# Recipes to crunch/compress graphics
.cgx.ccr:
	@$(CRU) $< $*.CCR

.scr.pcr:
	@$(CRU) $< $*.PCR

# Everything that should be done when make is executed
all: allcols msprites crunch sf.sfc donebld

# Recipe to pack palettes
allcols:
	@cd DATA\COL
	@pc.bat
	@cd ..\..

# FXGFX files to be interleaved
msprites: tex_01.bin tex_23.bin tex_23_a.bin

# MSPRITES .BIN recipes
tex_01.bin:
	@$(MERGE) MSPRITES\tex_0.CGX MSPRITES\tex_1.CGX MSPRITES\tex_01.bin $(MOPTS)

tex_23.bin:
	@$(MERGE) MSPRITES\tex_2.CGX MSPRITES\tex_3.CGX MSPRITES\tex_23.bin $(MOPTS)

tex_23_a.bin:
	@$(MERGE) MSPRITES\tex_2.CGX MSPRITES\tex_3_a.CGX MSPRITES\tex_23_a.bin $(MOPTS)

# Crunch all compressible GFX
crunch: $(CGXFILES) $(SCRFILES)

# The ROM Itself
sf.sfc: $(ALLFILES)
	@$(LINK) $(LOPTS) -osf.sfc @flist
	@$(EXTEND) sf.sfc $(EXTOPS)
	@$(CHECK) $(COPTS) sf.sfc
	@del msgs.txt

# Actions to perform when assembly is completed
donebld:
	@del BANK\*.SOB
	@copy sf.sfc ..\SF.SFC
	@del sf.sfc
	@copy symbols.txt ..\symbols.txt
	@del symbols.txt

# Clean everything up
clean:
	@del BANK\*.SOB
	@del MSPRITES\*.BIN
	@del DATA\COL\ALLCOLS.COL
	@del DATA\COL\*.PAC
	@del DATA\*.CCR
	@del DATA\*.PCR
	@del msgs.txt
	@del sf.sfc
	@del symbols.txt

## Banks to assemble

## Banks 0, 32
bank0.sob: \
BANK\bank0.ASM \

## Banks 1, 41
bank1.sob: \
BANK\BANK1.ASM \

## Banks 2, 3, 31, 36
bank2.sob: \
BANK\BANK2.ASM

## Bank 4
bank4.sob: \
BANK\BANK4.ASM

## Banks 5, 13, 39
bank5.sob: \
BANK\BANK5.ASM

## Banks 6, 33
bank6.sob: \
BANK\BANK6.ASM

## Bank 7
bank7.sob: \
BANK\BANK7.ASM

## Bank 8
bank8.sob: \
BANK\BANK8.ASM

## Bank 9
bank9.sob: \
BANK\BANK9.ASM

## Bank 10
bank10.sob: \
BANK\BANK10.ASM

## Banks 11, 40
bank11.sob: \
BANK\BANK11.ASM

## Banks 12, 14, 15, 16, 17, 37, 38
shbanks.sob: \
BANK\SHBANKS.ASM

## Banks 18, 19, 20, 21, 22, 23, 35 
incbins.sob: \
BANK\INCBINS.ASM


