; ################################
; ## UltraStarFox Configuration ##
; ################################

; This is the master configuration file. to configure various aspects of the game, go to the following files:

; Config file includes
;#############################################
	include CONFIG\ROM.INC		; ROM/Cartridge
	include CONFIG\XCESSORY.INC	; Accessories
	include	CONFIG\GAME.INC		; Game
	include	CONFIG\DEBUG.INC	; Debugging
	include CONFIG\GRAPHICS.INC ; Graphics
	include	CONFIG\LANGUAGE.INC	; Language
;#############################################
