	include	INC\header.inc
	include	INC\strathdr.inc
	include	EXT\gstrats.ext
	include	EXT\gastrats.ext
	include	EXT\ga2strat.ext
	include	EXT\gb2strat.ext
	include	EXT\strings.ext
	include	EXT\gcstrats.ext
	include	EXT\pistrats.ext
	include	EXT\pstrats.ext
	include	EXT\dstrats.ext
	include	INC\shmacs.inc
	include	EXT\expstrat.ext
	include	EXT\bootnmi.ext

	bank	7
	incfile	STRAT\gistrats.asm
	incfile	STRAT\gb3strat.asm
	bankend	7

	include	INC\tail.inc

