	IFD	_ARGSFX
; Restored SASM birthdays for ARGSFX

	IFEQ	_MONTH-8
	IFEQ	_DAY-6
	PRINTF	"Happy birthday Krister!%n"
	ENDC
	ENDC

	IFEQ	_MONTH-3
	IFEQ	_DAY-30
	PRINTF	"Happy birthday Giles!%n"
	ENDC
	ENDC

	IFEQ	_MONTH-2
	IFEQ	_DAY-18
	PRINTF	"Happy birthday Dylan!%n"
	ENDC
	ENDC
	ENDC	;_ARGSFX

; Birthdays! (SASM has them for the SF dev team, so why not for us?)

	IFEQ	_MONTH-12
	IFEQ	_DAY-7
	printf	"Happy birthday UltraStarFox!%n"
	ENDC
	ENDC

	IFEQ	_MONTH-8
	IFEQ	_DAY-26
	printf	"Happy birthday Kando!%n"
	ENDC
	ENDC

	IFEQ	_MONTH-4
	IFEQ	_DAY-5
	printf	"Happy birthday Sunlit!%n"
	ENDC
	ENDC

	IFEQ	_MONTH-9
	IFEQ	_DAY-22
	printf	"Happy birthday Monika!%n"
	ENDC
	ENDC
