	defalx	sWPx1,2
	defalx	sWPy1,2
	defalx	sWPz1,2
	defalx	expstratptr,3	; ptr to explosion strategy routine
	defalx	collstratptr,3	; ptr to collision strategy routine
	defalx	Endcollstratptr,3	; ptr to end collision strategy routine
	defalx	tempstratptr,3
	defalx	stratstate,1	; 
	defalx	fireobjptr,2
	defalx	depthoffset,2
	defalx	relposx,1	; CAN REMOVE THIS IF NEEDS BE
	defalx	relposy,1	; CAN REMOVE THIS IF NEEDS BE
	defalx	relposz,1	; CAN REMOVE THIS IF NEEDS BE
	defalx	debrisshape,2

;	defalx	motherobjptr,2
;	defalx	nextchildobjptr,2
;	defalx	childID,1

