; MOJI_2.FON CHARMAP
; Starts from ASCII 'A' ($41)
; Based on https://github.com/SpyderTL/StarFoxDisassembly/blob/master/graphics/objfont.txt
m2_nul	equ		$00 ; String terminator (not an actual part of MOJI2.FON)
m2_a	equ		$01
m2_b	equ		$02
m2_c	equ		$03
m2_d	equ		$04
m2_e	equ		$05
m2_f	equ		$06
m2_g	equ		$07
m2_h	equ		$08
m2_i	equ		$09
m2_j	equ		$0A
m2_k	equ		$0B
m2_l	equ		$0C
m2_m	equ		$0D
m2_n	equ		$0E
m2_o	equ		$0F
m2_p	equ		$10
m2_q	equ		$11
m2_r	equ		$12
m2_s	equ		$13
m2_t	equ		$14
m2_u	equ		$15
m2_v	equ		$16
m2_w	equ		$17
m2_x	equ		$18
m2_y	equ		$19
m2_z	equ		$1A
m2_ds	equ		$1B ; '-'
m2_0	equ		$1C
m2_1	equ		$1D
m2_2	equ		$1E
m2_3	equ		$1F
m2_4	equ		$20
m2_5	equ		$21
m2_6	equ		$22
m2_7	equ		$23
m2_8	equ		$24
m2_9	equ		$25
m2_ex	equ		$26 ; '!'
m2_qu	equ		$27 ; '?'
m2_sp	equ		$28 ; ' '
m2sf_S	equ		$29
m2sf_T	equ		$2A
m2sf_A	equ		$2B
m2sf_R	equ		$2C
m2sf_sp	equ		$2D ; ' '
m2sf_F	equ		$2E
m2sf_O	equ		$2F
m2sf_X	equ		$30
; $31-$40 unused
m2_pc	equ		$41 ; '%'