;###################
;# MSU-1 TRACK IDS #
;###################

; -- OPENING --
	msutrack	introdemo,1	;Intro Demonstration
	msutrack	title,2	;Title Screen
	msutrack	controls,3	;Controls
	msutrack	trainingmode,4	;Training
	msutrack	map,5	;Map
	msutrack	briefing,6	;Map Briefing Zoom
	msutrack	briefingshort,7	;Map Briefing Zoom Short
	msutrack	scramble,9	;SCRAMBLE Sequence

; -- MAIN STAGES  --
	; route 1
	msutrack	level1_1,10 ;Corneria
	msutrack	level1_2,11 ;Asteroid/Venom Orbital
	msutrack	level1_3,12 ;Space Armada
	msutrack	level1_4,13 ;Meteor
	msutrack	level1_6,14 ;Venom Surface
	; route 2
	msutrack	level2_2,15 ;Sector X / Z
	msutrack	level2_3,16 ;Titania
	msutrack	level2_4,17 ;Sector Y
	msutrack	level2_6,18 ;Venom Rt. 2
	; route 3
	msutrack	level3_3,19 ;Fortuna
	msutrack	level3_5,20 ;Macbeth

; -- STAGE BOSSES --
	; route 1
	msutrack	boss1_1,21 ;Boss Corneria
	msutrack	boss1_2,22 ;Boss Asteroid
	msutrack	boss1_3,23 ;Boss Space Armada
	msutrack	boss1_4,24 ;Boss Meteor
	; route 2
	msutrack	boss2_3,25 ;Boss Titania
	; route 3
	msutrack	boss3_3,26 ;Boss Fortuna
	msutrack	boss3_5,27 ;Boss Macbeth
	; common
	msutrack	boss1_5a,28 ;Phantron II
	msutrack	boss1_5b,29 ;Great Commander
	msutrack	boss1_5c,30 ;Phantron I
	msutrack	bossandross,31 ;Boss Andross
	; bonus
	msutrack	bossootd,32 ;Slot Machine

; -- SECRET LEVELS --
	msutrack	levelblackhole,33 ;Black Hole
	msutrack	levelootd,34 ;Out of this Dimension

; -- MISC --
	msutrack	enteringdangerousterritory,35 ;Entering Dangerous Territory
	msutrack	staffroll,36 ;Staff Roll
	msutrack	secretactivated,37 ;Secret Activated
	msutrack	gameenddemo,38
	msutrack	gameover,39	;Game Over
	msutrack	clearband,40	;Stage Clear (Band)
	msutrack	clearorch,41	;Stage Clear (Orch)
	msutrack	downband,42	;Player Down (Band)
	msutrack1	downorch,43	;Player Down (Orch)
; EOF