;###################
;# MSU-1 TRACK IDS #
;###################

; -- OPENING --
	msutrack	titledemo,1			;Title Demonstration
	msutrack	title,2				;Title Screen
	msutrack	controls,3			;Controls Select
	msutrack	trainingmode,4		;Training
	msutrack	map,5				;Map
	msutrack	briefing,6			;Map Briefing Zoom
	msutrack	briefingshort,7		;Map Briefing Zoom (Short)
	msutrack	scramble,9			;Emergency Call (SCRAMBLE Sequence)

; -- MAIN STAGES  --
	; route 1
	msutrack	level1_1,10 		;Corneria 1/2/3
	msutrack	level1_2,11			;Asteroid/Venom Orbital (1-2, 1-5, 3-2, 3-6)
	msutrack	level1_3,12 		;Space Armada
	msutrack	level1_4,13 		;Meteor
	msutrack	level1_6,14 		;Venom Base 1/3 (Venom Surface)
	; route 2
	msutrack	level2_2,15 		;Sector X / Z
	msutrack	level2_3,16 		;Titania
	msutrack	level2_4,17 		;Sector Y
	msutrack	level2_6,18 		;Venom Rt. 2
	; route 3
	msutrack	level3_3,19 		;Fortuna
	msutrack	level3_5,20 		;Macbeth

; -- STAGE BOSSES --
	; route 1
	msutrack	boss1_1,21 			;Boss Corneria 1/2/3 (Attack Carrier/Destructor)
	msutrack	boss1_2,22 			;Boss Asteroid 1/3 (Rock Crusher/Blade Barrier)
	msutrack	boss1_3,23 			;Boss Space Armada (Boss of Core Type) (Space Armada/Sector Z, Atomic Base I+II)
	msutrack	boss1_4,24 			;Boss Meteor (Dancing Insector)
	; route 2
	msutrack	boss2_3,25 			;Boss Titania (Prof. Hanger)
	; route 3
	msutrack	boss3_3,26 			;Boss Fortuna (Monarch Dodora)
	msutrack	boss3_5,27 			;Boss Macbeth (Spinning Core)
	; common
	msutrack	boss1_5a,28 		;Boss (Venom Base 2) (Venom 1, Phantron II)
	msutrack	boss1_5b,29 		;Boss (Venom Base Extended) (Venom 3, Great Commander I+II)
	msutrack	boss1_5c,30 		;Boss (Venom Base Short) (Venom 1+2, Phantron I/Mad Trucker/Galactic Rider)
	msutrack	bossandross,31 		;Boss Andross
	; bonus
	msutrack	bossootd,32 		;Boss Slot Machine

; -- SECRET LEVELS --
	msutrack	levelblackhole,33 	;Black Hole
	msutrack	levelootd,34 		;Out of this Dimension

; -- MISC --
	msutrack	dangerous,35 		;Entering Dangerous Territory
	msutrack	staffroll,36 		;Staff Roll
	msutrack	secretactivated,37 	;Secret Activated
	msutrack	gamecleardemo,38	;Game End Demonstration
	msutrack	bossroll,39			;Ending (Boss) (Boss Roll)
	msutrack	gameover,40			;Game Over
	msutrack	clearband,41		;Stage Clear (Band)
	msutrack	clearorch,42		;Stage Clear (Orch)
	msutrack	downband,43			;Player Down (Band)
	msutrack	downorch,44			;Player Down (Orch)
	msutrack	enterhyperspace1,45	;Warp Drive Spool (Asteroid Warp)
	msutrack	exithyperspace,46	;Exit Hyperspace (Coming out of Warp Speed)
	msutrack	continue,47			;Continue
	msutrack	lastbossclear,48	;Last Boss Clear
	msutrack	clearootd,49		;Clear (Out of this Dimension)
	msutrack	blackholewarp,50	;Black Hole Warp
	msutrack	enterhyperspace2,51	;Warp Drive Engage (Asteroid Warp Out)
	msutrack	blackholemap,52		;Black Hole/OOTD Map
; EOF