;###################
;# MSU-1 TRACK IDS #
;###################

; -- OPENING --
	msutrack	titledemo,1			;Title Demonstration
	msutrack	title,2				;Title Screen
	msutrack	controls,3			;Controls Select
	msutrack	trainingmode,4		;Training
	msutrack	map,5				;Map
	msutrack	blackholemap,6		;Black Hole/OOTD Map
	msutrack	briefing,7			;Map Briefing Zoom (long, 3D stage icons)
	msutrack	briefingshort,8		;Map Briefing Zoom (Short, 2D stage icons)
	msutrack	scramble,9			;Emergency Call (SCRAMBLE Sequence)

; -- MAIN STAGES  --
	; route 1
	msutrack	level1_1,10			;Corneria 1/2/3
	msutrack	level1_2,11			;Asteroid/Venom Orbital (1-2, 1-5, 3-2, 3-6)
	msutrack	level1_3,12			;Space Armada
	msutrack	level1_4,13			;Meteor
	msutrack	level1_6,14			;Venom Base 1/3 (Venom Surface)
	; route 2
	msutrack	level2_2,15			;Sector X / Z
	msutrack	level2_3,16			;Titania
	msutrack	level2_4,17			;Sector Y
	msutrack	level2_6,18			;Venom Base 2
	; route 3
	msutrack	level3_3,19			;Fortuna
	msutrack	level3_5,20			;Macbeth

; -- STAGE BOSSES --
	; route 1
	msutrack	boss1_1,21			;Boss Corneria 1/2/3 (Attack Carrier/Destructor)
	msutrack	boss1_2,22			;Boss Asteroid 1/3 (Rock Crusher/Blade Barrier)
	msutrack	boss1_3,23			;Boss Space Armada (Boss of Core Type) (Space Armada/Sector Z, Atomic Base I+II)
	msutrack	boss1_4,24			;Boss Meteor (Dancing Insector)
	; route 2
	msutrack	boss2_3,25			;Boss Titania (Prof. Hanger)
	; route 3
	msutrack	boss3_3,26			;Boss Fortuna (Monarch Dodora)
	msutrack	boss3_5,27			;Boss Macbeth (Spinning Core)
	; common
	msutrack	boss1_5a,28			;Boss (Venom Base 1) (Venom 1, Phantron II)
	msutrack	boss1_5b,29			;Boss (Venom Base Extended) (Venom 3, Great Commander I+II)
	msutrack	boss1_5c,30			;Boss (Venom Base Short) (Venom 1+2, Phantron I/Mad Trucker/Galactic Rider)
	msutrack	bossandross,31		;Boss Andross
	; bonus
	msutrack	bossootd,32			;Boss Slot Machine

; -- SECRET LEVELS --
	msutrack	levelblackhole,33	;Black Hole
	msutrack	levelootd,34		;Out of this Dimension

; -- JINGLES, FANFARES, AND SUCHLIKE --
	msutrack	clearband,35		;Stage Clear (Band)
	msutrack	clearorch,36		;Stage Clear (Orch)
	msutrack	clearootd,37		;Clear (OOTD)
	msutrack	downband,38			;Player Down (Band)
	msutrack	downorch,39			;Player Down (Orch)
	msutrack	gameover,40			;Game Over
	msutrack	continue,41			;Continue
	msutrack	secretactivated,42	;Secret Activated (Enter OOTD)
	msutrack	blackholewarp,43	;Black Hole Warp (Enter Black Hole)
	msutrack	blackholeexit,44	;Black Hole Warp Out
	msutrack	dangerous,45		;Entering Dangerous Territory

; -- ENDING SEQUENCE --
	msutrack	lastbossclear,46	;Last Boss Clear
	msutrack	gamecleardemo,47	;Game End Demonstration
	msutrack	bossroll,48			;Ending (Boss) (Boss Roll)
	msutrack	staffroll,49		;Staff Roll

; -- SOUND EFFECTS --
	msutrack	enterhyperspace1,50	;Warp Drive Spool (Asteroid Warp)
	msutrack	enterhyperspace2,51	;Warp Drive Engage (Asteroid Warp Out)
	msutrack	exithyperspace,52	;Coming out of Warp Speed (Exit hyperspace)
; EOF