bgm_map		equ	1
bgm_planet		equ	3
bgm_space		equ	4
bgm_boss		equ	5
bgm_boss1		equ	5
bgm_fanfare		equ	7
bgm_mapselect		equ	$b
bgm_mapselectshort	equ	$d

bgm_allclear	equ	$f0
bgm_fadeout		equ	$f1
bgm_transmit	equ	$ff

pse_stop		equ	$00
pse_low		equ	$01
pse_mid		equ	$02
pse_high		equ	$03

se_pauseoff		equ	$01
se_pauseon		equ	$02
se_playerdown	equ	$03
se_playerdamage	equ	$04
se_wingdestructleft	equ	$05
se_wingdestructright	equ	$06
se_wingdamageleft	equ	$07
se_wingdamageright	equ	$08
se_wingtouchleft	equ	$09
se_wingtouchright	equ	$0a
se_warning1		equ	$0b
se_warning2		equ	$0c

se_gateofring	equ	$0f
se_itemcatch	equ	$10
se_cursor		equ	$11

se_destructbossnear	equ	$1e
se_destructbossmid	equ	$1f
se_destructbossfar	equ	$20
se_destructenemynear	equ	$21
se_destructenemymid	equ	$22
se_destructenemyfar	equ	$23
se_damageenemynear	equ	$24
se_damageenemymid	equ	$25
se_damageenemyfar	equ	$26
se_hitwallnear	equ	$27
se_hitwallmid	equ	$28
se_hitwallfar	equ	$29

se_specialweapon	equ	$30
se_abutton		equ	$31

se_speedup		equ	$32
se_speeddown		equ	$33

se_laser		equ	$35

se_missilenear	equ	$3c
se_missilemid	equ	$3d
se_missilefar	equ	$3e

se_movingwallleft	equ	$3f
se_movingwallcentre	equ	$40
se_movingwallright	equ	$41
se_movingwallmid	equ	$42
se_movingwallfar	equ	$43

se_laserleft		equ	$44
se_lasercentre	equ	$45
se_laserright	equ	$46
se_lasermid		equ	$47
se_laserfar		equ	$48

se_enemybattrynear	equ	$49
se_enemybattrymid	equ	$4a
se_enemybattryfar	equ	$4b

se_dopright		equ	$6d
se_dopcentre	equ	$6e
se_dopleft		equ	$6f

se2_other		equ	%0001
se2_flight		equ	%0010
se2_walker		equ	%0011
se2_ufo		equ	%0100
se2_shutter		equ	%0101
se2_missile		equ	%0110
se2_burst		equ	%0111



