	defal	stratptr,3		; ptr to strategy routine
	defal	immuneptr,2		; ptr. to immunity object
	defal	collobjptr,2		; ptr to collision object
	defal	sflags,1		; strategy flags.
	defal	sflags2,1		; strategy flags.
	defal	sflags3,1		; strategy flags.
	defal	sflags4,1		; strategy flags.
	defal	skidy,1
	defal	sbyte1,1
	defal	sbyte2,1
	defal	sbyte3,1
	defal	sbyte4,1
	defal	sword1,2
	defal	sword2,2
	defal	HP,1
	defal	AP,1
	defal	collcount,1		; collision time counter.
	defal	collflags,1		; collision flags.
	defal	vx,2
	defal	vy,2
	defal	vz,2
	defal	hitflags,1

	defal	weaponnum,1
	defal	openal,1

